"""Token count included in Models

Revision ID: 0253d99ef9e0
Revises: 534a0eed2513
Create Date: 2023-03-12 14:58:09.734890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0253d99ef9e0'
down_revision = '534a0eed2513'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('tokens_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'tokens_used')
    # ### end Alembic commands ###
