"""Users with Verify Password

Revision ID: 17e513d6287f
Revises: e54241dddec8
Create Date: 2023-03-19 16:13:52.040848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e513d6287f'
down_revision = 'e54241dddec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
