"""Delete Scholar field

Revision ID: 1f2c8388e9cd
Revises: 57e76430b247
Create Date: 2023-04-02 14:06:50.413145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2c8388e9cd'
down_revision = '57e76430b247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scholar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scholar', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
