"""Chat ranking System

Revision ID: 4110795b481d
Revises: 164f4718b239
Create Date: 2023-03-28 11:20:23.430676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4110795b481d'
down_revision = '164f4718b239'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('alt_response', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'alt_response')
    # ### end Alembic commands ###
