"""Chat ranking System

Revision ID: 4affb450eed8
Revises: db28146501c9
Create Date: 2023-03-22 16:17:19.844830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4affb450eed8'
down_revision = 'db28146501c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
