"""Adding Scholar Field to User

Revision ID: 507dd713df82
Revises: 
Create Date: 2023-04-02 06:38:31.495805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507dd713df82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scholar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scholar')
    # ### end Alembic commands ###
