"""API endpoints to get Chat History

Revision ID: 534a0eed2513
Revises: 9b03693e13e4
Create Date: 2023-03-10 01:55:44.922857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534a0eed2513'
down_revision = '9b03693e13e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
