"""Chats upgraded to save complete chatlog

Revision ID: 55439a9af52b
Revises: 47c09356a020
Create Date: 2023-03-09 22:04:06.982741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55439a9af52b'
down_revision = '47c09356a020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
