"""changed scholar field from boolean to string

Revision ID: 57e76430b247
Revises: 8cd287c9dff2
Create Date: 2023-04-02 14:05:26.647452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e76430b247'
down_revision = '8cd287c9dff2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
