"""Redo scholar as boolean

Revision ID: 7611ecea0ba1
Revises: d80e6cd24d18
Create Date: 2023-04-02 14:25:41.567854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7611ecea0ba1'
down_revision = 'd80e6cd24d18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scholar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scholar')
    # ### end Alembic commands ###
