"""Chat ranking altresponse added

Revision ID: 876d14d01c00
Revises: 4affb450eed8
Create Date: 2023-03-22 17:37:32.283317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876d14d01c00'
down_revision = '4affb450eed8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
