"""Deleted Scholar Field

Revision ID: ae7f11d56bce
Revises: 507dd713df82
Create Date: 2023-04-02 06:47:40.108087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7f11d56bce'
down_revision = '507dd713df82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scholar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scholar', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
