"""delete scholar again

Revision ID: d80e6cd24d18
Revises: 9a11ed16f2af
Create Date: 2023-04-02 14:25:12.424299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80e6cd24d18'
down_revision = '9a11ed16f2af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scholar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scholar', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
