"""Chat ranking System

Revision ID: db28146501c9
Revises: f1f22ab293e4
Create Date: 2023-03-22 02:32:32.421977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db28146501c9'
down_revision = 'f1f22ab293e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('response_rating', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('alt_response', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'alt_response')
    op.drop_column('chats', 'response_rating')
    # ### end Alembic commands ###
