"""Token count included in Models

Revision ID: e54241dddec8
Revises: 0253d99ef9e0
Create Date: 2023-03-12 15:01:55.650249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54241dddec8'
down_revision = '0253d99ef9e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
