"""Changed First and Last Name from Users to Profile

Revision ID: f1f22ab293e4
Revises: 17e513d6287f
Create Date: 2023-03-21 14:37:47.480906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f22ab293e4'
down_revision = '17e513d6287f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    # ### end Alembic commands ###
